services:
  - type: web
    name: football-betting-bot-api
    env: python
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ODDS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TWITTER_API_KEY
        sync: false
      - key: TWITTER_API_SECRET
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN
        sync: false
      - key: TWITTER_ACCESS_TOKEN_SECRET
        sync: false